-- Question 7

with base as (
	select
		  sales_rep_id
		, sum(order_total) as total_order_value_generated
	from dbo.fact_orders
	where order_status = 'Completed'
	group by sales_rep_id
)

, manager_details as (
	select
		  de.employee_id
		, de.employee_name
		, de.manager_id
		, de.role
		, b.total_order_value_generated
	from dbo.dim_employee de
	left join base b
		on de.employee_id = b.sales_rep_id
)

, team_total_revenue as (
	select
		  employee_id
		, employee_name
		, role
		, manager_id
		, total_order_value_generated as team_total_revenue
	from manager_details
	where total_order_value_generated is not null

	union all

	select
		  md1.employee_id
		, md1.employee_name
		, md1.role
		, md1.manager_id
		, ttr.team_total_revenue
	from manager_details md1
	join team_total_revenue ttr
		on md1.employee_id = ttr.manager_id
)

select
	  employee_id
	, employee_name
	, role
	, sum(team_total_revenue) as team_total_revenue
from team_total_revenue
group by employee_id, employee_name, role
option (maxrecursion 200);

-- Approach:
-- Aggregated completed order value by sales representative, then used
-- the employee hierarchy to recursively move each representative's
-- revenue up through their managers. Finally, summed the propagated
-- revenue for each employee to calculate their total team revenue.

-- Result:
-- Returns each employee's total completed order value generated by
-- themselves and everyone reporting under them at any level.